### ISSUE TITLE
Netiquette

### ISSUE THREAD

**Issue by gonzaloserrano** [bcneng/bcneng#8]
We should have a netiquette to clear certain points of the slack use:

## company profiles 
Allowing or not company profiles, as explained by @ignasi35's comment here https://github.com/bcneng/bcneng/pull/7#issuecomment-374589167
> Recently a non-personal account representing a company showed up trying to hire people. While 'm not against users promoting their job offers on the appropriate channels I think using non-personal accounts is a no-no. I'm not sure how to reflect that on this CoC. WDYT?

## hiring

- offers from outside BCN/Catalunya that don't allow full (or partial?) remote

## others

- see if admins can move messages to their appropiate channels (e.g someone posting in hiring-discussions or general instead of hiring-billboard etc)

----

More ideas are welcome. We can move each one of them in its own issue to be voted by the community.

We also should post them in the website (think about @ignasi35's idea of using github pages instead of the current web)

**Comment by sdecandelario** [comment]
For me about the hiring section make sens to have two types of offers:
* A remote position, doesn't matter the location
* An in site position in the area of Catalonia

The other cases I think don't make sense because the scope of the slack is the area of Barcelona, but I think we can accept Catalonia area because if anyone want to move to the location of the offer.

**Comment by gonzaloserrano** [comment]
I've added a PR implementing some of the stuff talked here: https://github.com/bcneng/bcneng/pull/10
